import 'app_localization.dart';

typedef _PlaceNames = ({String chinese, String english});

String localizedWorldPlaceName({
  required String id,
  required String fallback,
  required AppLanguage language,
}) {
  if (language == AppLanguage.japanese) return fallback;
  final names = _worldPlaceNames[id];
  if (names == null) return fallback;
  return language == AppLanguage.chinese ? names.chinese : names.english;
}

// Names follow the original world-map localization table. Japanese remains in
// world_hierarchy.json, which is also the fallback for unknown future IDs.
const Map<String, _PlaceNames> _worldPlaceNames = {
  'area_01': (chinese: '库肯岛周边地区', english: 'Kurken Island Area'),
  'field_01_001': (chinese: '库肯岛', english: 'Kurken Island'),
  'stage_01_001_01': (chinese: '尖塔的蓄水池', english: 'Steeple Reservoir'),
  'stage_01_001_02': (chinese: '魔石灯塔', english: 'Fairystone Lighthouse'),
  'stage_01_001_04': (chinese: '莱莎家', english: "Ryza's Home"),
  'stage_01_001_05': (chinese: '山羊放牧场', english: 'Goat Pasture'),
  'stage_01_001_06': (chinese: '休憩广场', english: 'Relaxing Plaza'),
  'stage_01_001_08': (chinese: '水源的瀑底潭', english: 'Waterfall Basin'),
  'field_01_002': (chinese: '小妖精森林', english: 'Pixie Forest'),
  'stage_01_002_01': (chinese: '藏身处前', english: 'In front of the Hideout'),
  'stage_01_002_02': (chinese: '彩花圆环', english: 'Flower Ring'),
  'stage_01_002_03': (chinese: '灯笼树', english: 'Lantern Tree'),
  'stage_01_002_04': (chinese: '树桩舞台', english: 'Stump Stage'),
  'field_01_003': (chinese: '旅人之路', english: "Traveler's Road"),
  'stage_01_003_01': (chinese: '对岸的沙滩', english: 'Beach of Far Bank'),
  'stage_01_003_02': (chinese: '大鼬花园', english: "Weasels' Flower Garden"),
  'stage_01_003_03': (chinese: '旧街道遗迹', english: 'Old Highway Ruins'),
  'stage_01_003_04': (chinese: '分道大树', english: 'Road Fork Tree'),
  'stage_01_003_05': (chinese: '罕见者祭坛', english: 'Scarce Altar'),
  'field_01_004': (chinese: '水没坑道', english: 'Sunken Mine'),
  'stage_01_004_01': (chinese: '噬魔树的水边', english: 'Evileater Tree Shore'),
  'stage_01_004_02': (chinese: '离去少女的水镜', english: "Maiden's Mirror"),
  'stage_01_004_03': (chinese: '河畔岩壁', english: 'Riverside Rock Wall'),
  'field_01_005': (chinese: '隐秘的海湾', english: 'Hidden Cove'),
  'stage_01_005_01': (chinese: '圣堂前的秘密海岸', english: 'Hidden Cove Temple'),
  'stage_01_005_02': (chinese: '不报时的大钟', english: 'Silent Bell'),
  'stage_01_005_03': (chinese: '封印祭坛', english: 'Sealed Altar'),
  'field_01_006': (chinese: '流星古城', english: 'Meteor Castle'),
  'stage_01_006_01': (chinese: '凌乱的宝库', english: 'Pillaged Treasure Trove'),
  'stage_01_006_02': (chinese: '旧王国的守护龙雕像', english: 'Dragon Statue'),
  'field_01_007': (chinese: '魏斯伯格火山', english: 'Weissberg Volcano'),
  'stage_01_007_01': (chinese: '古老吊桥', english: 'Old Drawbridge'),
  'stage_01_007_02': (chinese: '工匠村遗址', english: 'Artisan District Ruins'),
  'stage_01_007_03': (chinese: '黑铁祭坛', english: 'Black Iron Altar'),
  'field_01_008': (chinese: '枫叶三角洲', english: 'Maple Delta'),
  'stage_01_008_01': (chinese: '蜜潭', english: 'Honey Pool'),
  'stage_01_008_02': (chinese: '狭缝小岛', english: 'Middle Islet'),
  'field_01_009': (chinese: '里甾峡谷', english: 'Liese Valley'),
  'stage_01_009_01': (chinese: '峡谷之门', english: 'Canyon Gate'),
  'stage_01_009_02': (chinese: '石巨人塚', english: "Stone Giant's Mound"),
  'stage_01_009_03': (chinese: '门前大阶梯', english: 'Grand Stairway'),
  'field_01_010': (chinese: '匹欧尼尔圣塔', english: 'Pynnor Holy Tower'),
  'stage_01_010_01': (chinese: '连接圣塔的桥', english: 'Holy Towers Bridge'),
  'field_01_011': (chinese: '被遗忘的废村', english: 'Abandoned Village'),
  'stage_01_011_01': (chinese: '往昔的集会所', english: 'Former Meeting Place'),
  'stage_01_011_02': (chinese: '废弃的中央广场', english: 'Abandoned Central Square'),
  'stage_01_011_03': (chinese: '瞭望社殿', english: 'Guards Shrine'),
  'stage_01_011_04': (chinese: '红之庭院', english: 'Crimson Garden'),
  'field_01_012': (chinese: '古老大宅邸', english: 'Old Mansion'),
  'stage_01_012_01': (chinese: '喷水池庭园', english: 'Water Fountain Park'),
  'stage_01_012_02': (chinese: '冷清的厨房', english: 'Deserted Cooking Area'),
  'stage_01_012_03': (chinese: '无歌舞台', english: 'Songless Stage'),
  'field_01_013': (chinese: '柯克群岛', english: 'Kark Isles'),
  'stage_01_013_01': (chinese: '沐光大树', english: 'Tree of Light'),
  'stage_01_013_02': (chinese: '占星高地', english: 'Star Gazing Hill'),
  'stage_01_013_03': (chinese: '大灯塔', english: 'Big Lighthouse'),
  'stage_01_013_04': (chinese: '碧命泉', english: 'Blue Life Spring'),
  'stage_01_013_05': (chinese: '喷烟丘陵', english: 'Erupting Hill'),
  'stage_01_013_06': (chinese: '三剑之地', english: 'Land of Three Swords'),
  'field_01_014': (chinese: '万象大典', english: 'Code of the Universe'),
  'stage_01_014_01': (chinese: '万象大典', english: 'Code of the Universe'),
  'area_02': (chinese: '克莱莉亚地区', english: 'Cleria region'),
  'field_02_001': (chinese: '采掘街道', english: 'Mining Highway'),
  'stage_02_001_01': (chinese: '旧采掘场遗迹', english: 'Old Mining Site Ruins'),
  'stage_02_001_02': (chinese: '水源的清湖', english: 'Lake Source'),
  'stage_02_001_03': (chinese: '小港都', english: 'Small Port City'),
  'field_02_002': (chinese: '萨多尼卡', english: 'Sardonica'),
  'stage_02_002_01': (
    chinese: '工匠公会总部',
    english: "Artisans' Union Headquarters",
  ),
  'stage_02_002_02': (chinese: '玛尔摩广场', english: 'Marmo Square'),
  'stage_02_002_03': (chinese: '玻璃工艺工房', english: 'Glasswork Workshop'),
  'stage_02_002_04': (chinese: '魔石工房', english: 'Fairystone Workshop'),
  'field_02_003': (chinese: '阿斯托拉德高地', english: 'Astrad Heights'),
  'stage_02_003_01': (chinese: '大结晶灯火', english: 'Large Crystal Light'),
  'stage_02_003_02': (chinese: '巨大水车', english: 'Giant Water Wheel'),
  'stage_02_003_03': (chinese: '矿山休息处', english: 'Mine Resthouse'),
  'stage_02_003_04': (chinese: '采掘设施中心', english: 'Mining Facility Center'),
  'stage_02_003_05': (chinese: '旧魔石储藏库', english: 'Old Fairystone Silo'),
  'stage_02_003_06': (chinese: '熔岩坑道入口', english: 'Lava Mine Entrance'),
  'stage_02_003_07': (chinese: '尖晶森林', english: 'Spinel Forest'),
  'stage_02_003_08': (chinese: '森林藏身处', english: 'Hideout in the Forest'),
  'field_02_004': (chinese: '魔石运送路', english: 'Fairystone Cargo Route'),
  'stage_02_004_01': (chinese: '玻璃工艺工厂', english: 'Glasswork Building'),
  'stage_02_004_02': (chinese: '水晶壕沟', english: 'Crystal Ditch'),
  'stage_02_004_03': (chinese: '彩虹的魔力结晶', english: 'Rainbow Magic Crystal'),
  'stage_02_004_04': (chinese: '溪谷的涌水', english: 'Valley Spring Water'),
  'stage_02_004_05': (chinese: '幻晶大瀑布', english: 'Phantom Waterfall'),
  'stage_02_004_06': (chinese: '瀑底潭的河岛', english: 'Waterfall Basin Sandbank'),
  'field_02_005': (chinese: '火花矿山', english: 'Scintilla Mine'),
  'stage_02_005_01': (chinese: '彩绘玻璃回廊', english: 'Stained-Glass Corridor'),
  'stage_02_005_02': (chinese: '火花的地底湖', english: 'Scintilla Underground Lake'),
  'stage_02_005_03': (chinese: '逆转水晶', english: 'Inverted Crystal'),
  'area_03': (chinese: '内米德地区', english: 'Nemed region'),
  'field_03_001': (chinese: '波卢塔丘陵', english: 'Portta Hills'),
  'stage_03_001_01': (chinese: '海湾的渔村', english: 'Cove Fishing Village'),
  'stage_03_001_02': (chinese: '长苔藓的古塔', english: 'Old Moss-Covered Tower'),
  'stage_03_001_03': (chinese: '猎人的过夜处', english: "Hunters' Inn"),
  'stage_03_001_04': (chinese: '眺望之崖', english: 'Distant Cliff'),
  'stage_03_001_05': (chinese: '悬崖下的小离岛', english: 'Island Below the Cliff'),
  'field_03_002': (chinese: '内米德大森林', english: 'Nemed Forest'),
  'stage_03_002_01': (chinese: '弗雷村', english: 'Village of Faurre'),
  'stage_03_002_02': (chinese: '龙树', english: 'Dragon Tree'),
  'stage_03_002_03': (chinese: '正门前废墟群', english: 'Front Gate Ruins'),
  'stage_03_002_04': (chinese: '山间的部落', english: 'Village Between Mountains'),
  'stage_03_002_05': (chinese: '中央封锁区域', english: 'Central Blockade Area'),
  'stage_03_002_06': (chinese: '崩塌的屏障', english: 'Collapsed Wall'),
  'field_03_003': (chinese: '花道田园', english: 'Rural Flower Road'),
  'stage_03_003_01': (chinese: '菜田的部落', english: 'Village of Green Gardens'),
  'stage_03_003_02': (chinese: '沿岸灯塔', english: 'Coastal Lighthouse'),
  'stage_03_003_03': (chinese: '钟岬角', english: 'Bell Cape'),
  'field_03_004': (chinese: '龙尾大山道', english: 'Dragon Tail Trail'),
  'stage_03_004_01': (chinese: '四座尖塔', english: 'Four Steeples'),
  'stage_03_004_02': (chinese: '高地的火山臼', english: 'Caldera at the Hill'),
  'stage_03_004_03': (chinese: '崇高的噗尼雕像', english: 'Sublime Puni Statue'),
  'stage_03_004_04': (chinese: '岩山的神木', english: 'Rocky Mountain Tree'),
  'stage_03_004_05': (chinese: '大小不齐的底座', english: 'Uneven Pedestal'),
  'field_03_005': (chinese: '山顶的荒废神殿', english: 'Abandoned Temple'),
  'stage_03_005_01': (chinese: '无信仰的拜殿', english: 'Faithless Worship Hall'),
  'stage_03_005_02': (chinese: '通往最深处的吊桥', english: 'Depths Drawbridge'),
  'stage_03_005_03': (chinese: '纵贯大空洞', english: 'Grand Cavity'),
  'area_04': (chinese: '异界奥灵', english: 'Underworld Orim'),
  'field_04_001': (chinese: '乌尔迪斯圣迹', english: 'Holy Site of Urdis'),
  'stage_04_001_01': (chinese: '温德尔', english: 'Windle'),
  'stage_04_001_02': (chinese: '癫狂暗窟', english: 'Cavern of Insanity'),
  'stage_04_001_03': (chinese: '威势灵碑', english: 'Prestigious Monument'),
  'stage_04_001_04': (chinese: '通往旧迹的门扉', english: 'Gate to the Old Ruins'),
  'stage_04_001_05': (chinese: '古龙神祠', english: 'Old Dragon Shrine'),
  'stage_04_001_06': (chinese: '乌尔迪斯大树', english: 'Great Tree of Urdis'),
  'field_04_002': (chinese: '飞鸟山路', english: "Birds' Pass"),
  'stage_04_002_01': (chinese: '奏波之墓', english: 'Tomb of the Wave Tuners'),
  'stage_04_002_02': (chinese: '参拜道的小洞穴', english: 'Small Roadside Cave'),
  'stage_04_002_03': (chinese: '引导之岩', english: 'Guiding Rock'),
  'field_04_003': (chinese: '悠远之匣', english: 'Distant Box'),
  'stage_04_003_01': (chinese: '并立的巨像', english: 'A Row of Giant Statues'),
  'stage_04_003_02': (chinese: '映阳祭坛', english: 'Altar of Reflecting Sun'),
  'stage_04_003_03': (chinese: '受供奉的精灵石', english: 'Worshiped Spirit Stone'),
  'stage_04_003_04': (chinese: '纵断吊桥', english: 'Drawbridge Crossing'),
  'stage_04_003_05': (chinese: '太古的魔石壁', english: 'Ancient Fairystone Wall'),
  'area_05': (chinese: '王都周边地区', english: 'Capital Area'),
  'field_05_001': (chinese: '王都近郊', english: 'Capital Outskirts'),
  'stage_05_001_01': (chinese: '王都近郊', english: 'Capital Outskirts'),
  'field_05_002': (chinese: '王都阿斯拉・阿姆・伯特', english: 'Ashra-am Baird'),
  'stage_05_002_01': (chinese: '第一中央区', english: 'Erster Central District'),
  'stage_05_002_02': (chinese: '知识学园区', english: 'Weisheit Academy District'),
  'stage_05_002_03': (chinese: '清澄农耕区', english: 'Klares Farming District'),
  'stage_05_002_04': (chinese: '煤烟工匠区', english: 'Rauch Artisan District'),
  'field_05_003': (chinese: '风鸣谷', english: 'Valley of Winds'),
  'stage_05_003_01': (chinese: '风鸣谷', english: 'Valley of Winds'),
  'field_05_004': (chinese: '王都南方', english: 'Southern Outskirts'),
  'stage_05_004_01': (chinese: '王都南方', english: 'Southern Outskirts'),
  'field_05_005': (chinese: '北方大地', english: 'Northern Lands'),
  'stage_05_005_01': (chinese: '北方大地', english: 'Northern Lands'),
  'field_05_006': (chinese: '灵龙的棺木', english: "Ethereal Dragon's Coffin"),
  'stage_05_006_01': (chinese: '灵龙的棺木', english: "Ethereal Dragon's Coffin"),
  'field_05_007': (chinese: '古代玛那工房', english: 'Ancient Mana Workshop'),
  'stage_05_007_01': (chinese: '古代玛那工房', english: 'Ancient Mana Workshop'),
  'field_05_008': (chinese: '地底少女的墓地', english: "Maiden's Catacombs"),
  'stage_05_008_01': (chinese: '地底少女的墓地', english: "Maiden's Catacombs"),
  'field_05_009': (chinese: '水底的星都', english: 'Sunken City of Stars'),
  'stage_05_009_01': (chinese: '水底的星都', english: 'Sunken City of Stars'),
  'field_05_010': (chinese: '迷雾森林', english: 'Mirage Land'),
  'stage_05_010_01': (chinese: '迷雾森林', english: 'Mirage Land'),
  'field_05_012': (chinese: '传承的龙骨谷', english: 'Dragonbone Valley'),
  'stage_05_012_01': (chinese: '传承的龙骨谷', english: 'Dragonbone Valley'),
};
